### ISSUE TITLE
Form button should have a type of 'submit'

### ISSUE THREAD

**Issue by oliverjam** [shiryz/pg-workshop#13]
For a `button` to automatically submit a form it needs to have `type=submit` rather than `type=button`. I think this is actually the default for a `button` within a `form`, so it could also be left off entirely.

I'm happy to do a PR if you like

**Comment by emilyb7** [comment]
@oliverjam well spotted! we'll make you a contributor so you could fix it if you have time

**Comment by oliverjam** [comment]
@emilyb7 PR is ready if you want to give me access
