### ISSUE TITLE
handle errors

### ISSUE THREAD

**Issue by jsms90** [shiryz/pg-workshop#27]
Once PR #23 is merged, we need to change the solution to show errors being handled. Particularly after [the confusion from last week](https://github.com/foundersandcoders/london-curriculum/blob/e8f0b7951dce505264e625fa4dc2395eea404bb1/stop-go-continue/fac-11/cohort-week-5.md#go) over the [issues from the `error-handling-workshop`](https://github.com/foundersandcoders/error-handling-workshop/issues/17)
+ https://github.com/pbywater/pg-workshop/blob/solution/src/router.js#L15
+ https://github.com/pbywater/pg-workshop/blob/solution/src/router.js#L24
+ https://github.com/pbywater/pg-workshop/blob/solution/src/router.js#L36
+ https://github.com/pbywater/pg-workshop/blob/solution/src/router.js#L41
+ https://github.com/pbywater/pg-workshop/blob/solution/src/router.js#L52

**Comment by jsms90** [comment]
The readme in the [error handling workshop](https://github.com/foundersandcoders/error-handling-workshop) is really good, if you need help understanding how. There's also the [solution](https://github.com/foundersandcoders/error-handling-workshop/blob/master/acceptance/solution/handler.solution.js). But let me know if you need help on this.

**Comment by jsms90** [comment]
@pbywater When handling errors, it helps to think about it from the perspective of a user.

+ [Failure with GET request to `/` endpoint](https://github.com/foundersandcoders/pg-workshop/blob/solution/src/router.js#L13-L20)
+ [Failure of GET request for all other public files](https://github.com/pbywater/pg-workshop/blob/solution/src/router.js#L50-L57)

If there's a problem with reading `index.html` (or any other public file), the user basically isn't going to be able to see the content of your website at all. At this point, you might as well serve a 500. See [this example](https://github.com/FAC-11/week5-ASSKITTY/blob/master/src/handlers.js#L8-L16) & [this example](https://github.com/AbdullahChaudhry/week-5-CADJ/blob/master/src/handler.js#L19-L30) of how FAC11 have been dealing with these kind of errors in their projects so far.

+ [An error with `getData`](https://github.com/foundersandcoders/pg-workshop/blob/solution/src/router.js#L24)

You're currently throwing the error. Using "throw" will stop the whole application from running & the site will crash. Is that what you want to happen? (in some cases it might be)

Think about what the scenario is, in which this error will occur. What is `getData` doing? It's just a basic `SELECT * FROM` query. If there's a problem with selecting the users from the database, this is tantamount to an internal error. So I reckon you would probably want to serve a 500 error again. What content do you want to serve your users?

@eliascodes any comments?

**Comment by pbywater** [comment]
@jsms90 thanks! :)

**Comment by eliasmalik** [comment]
I didn't catch #29 before it was merged, but left some comments.
