### ISSUE TITLE
solutions branch does not work 

### ISSUE THREAD

**Issue by y-zaky** [shiryz/pg-workshop#32]
The solutions provided dont seem to allow you to create a user... :(

**Comment by jsms90** [comment]
@bowssy88 I don't experience any problems with this. Could you please explain the steps that you took to try and make this work, and exactly what problem you experience?

I have done:
1. Create local database
1. Create users table
1. Create `config.env`
1. Run `node solutions/src/server.js`
1. Entered a new name into the database

I then see the table updated in the DOM and if I query my local database from within psql, the table looks as you would expect.

**Comment by mattlub** [comment]
closing as this is now outdated
