### ISSUE TITLE
Refactor master with CSS in solution folder only

### ISSUE THREAD

**Issue by i2xzy** [shiryz/pg-workshop#35]
> After reviewing the pg-workshop with @shiryz and @MynahMarie , we decided to add the CSS from the solution into the main workshop.
> 
> I have created a branch with this change as well as some refactoring to encourage best practises with relation to abstracting handlers out of the router, handling static files and errors, using qs and the power of destructuring.

Based on reviews by @eliascodes  and @m4v15 I've separated the code into two branches. Both with the refactoring but one with CSS in the solution to be merged into master and one with CSS in the main workshop that can be used by cohorts if they want.

**Comment by i2xzy** [comment]
The pr will hopefully close issues #27 #31 and #32

**Comment by mattlub** [comment]
closing as the refactor was done in #34
